apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhdhpai802-final
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon/rhdhpai802-final:0f2d700325c1fc6c48866bc70a173847975d2ebf@sha256:d527bb63d9a6959de63fc0831199b81225eec5c4726f73ee47cf5f3daa52f941 # use pre-built to bootstrap
          name: app-inference
